//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsage
    {
        public int UsageID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> LessonID { get; set; }
        public Nullable<int> RentalID { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Lessons Lessons { get; set; }
        public virtual Rentals Rentals { get; set; }
    }
}
