//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorseClubDBEntities : DbContext
    {
        public HorseClubDBEntities()
            : base("name=HorseClubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentUsage> EquipmentUsage { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Horses> Horses { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffSchedule> StaffSchedule { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VetVisits> VetVisits { get; set; }
    }
}
