//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rentals()
        {
            this.EquipmentUsage = new HashSet<EquipmentUsage>();
        }
    
        public int RentalID { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
        public Nullable<System.TimeSpan> RentalTime { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> HorseID { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentUsage> EquipmentUsage { get; set; }
        public virtual Horses Horses { get; set; }
    }
}
