//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qq
{
    using System;
    using System.Collections.Generic;
    
    public partial class VetVisits
    {
        public int VisitID { get; set; }
        public Nullable<int> HorseID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Horses Horses { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
